// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywohajmeijjiubesykcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3b2hham1laWpqaXViZXN5a2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTM0NzIsImV4cCI6MjA3MTc4OTQ3Mn0.wK5qVZxcJfzREn38-J5Z8WiAFQrycNHWKmunwAc0-jA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});